using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FinalRemoveSubscription : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Companies_SubscriptionPlans_PlanId",
                table: "Companies");

            migrationBuilder.DropTable(
                name: "SubscriptionPlans");

            migrationBuilder.DropIndex(
                name: "IX_Companies_PlanId",
                table: "Companies");

            migrationBuilder.DropColumn(
                name: "AIAnalysis",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "PlanId",
                table: "Companies");

            migrationBuilder.DropColumn(
                name: "SubscriptionExpiresAt",
                table: "Companies");

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_AIRecommendation",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "AIAnalysis_AnalyzedAt",
                table: "JobApplications",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_AutoGeneratedSummary",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_EducationScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_ExperienceScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_ExtractedData_Certifications",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_Educations",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_ExtractedData_Languages",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_Skills",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_WorkExperiences",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_IdentifiedSkills",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_OverallScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_SkillsScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_Strengths",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "AIAnalysis_TotalYearsExperience",
                table: "JobApplications",
                type: "double precision",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_Weaknesses",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.InsertData(
                table: "Departments",
                columns: new[] { "Id", "CompanyId", "CreatedAt", "Description", "Name", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("d001d001-d001-d001-d001-d001d001d001"), new Guid("11111111-1111-1111-1111-111111111111"), new DateTime(2026, 4, 4, 21, 42, 36, 20, DateTimeKind.Utc).AddTicks(1279), null, "Tech & Innovation", null },
                    { new Guid("d002d002-d002-d002-d002-d002d002d002"), new Guid("11111111-1111-1111-1111-111111111111"), new DateTime(2026, 4, 4, 21, 42, 36, 20, DateTimeKind.Utc).AddTicks(2071), null, "Human Resources", null }
                });

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[] { "Id", "AvatarUrl", "CompanyId", "CreatedAt", "DepartmentId", "Email", "EmailConfirmationToken", "EmailConfirmed", "FirstName", "IsActive", "JobTitle", "LastLoginAt", "LastName", "MustChangePassword", "PasswordHash", "PasswordResetToken", "PasswordResetTokenExpiry", "PhoneNumber", "RefreshToken", "RefreshTokenExpiry", "Role", "UpdatedAt" },
                values: new object[,]
                {
                    { new Guid("10001000-1000-1000-1000-100010001000"), null, new Guid("11111111-1111-1111-1111-111111111111"), new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), new Guid("d002d002-d002-d002-d002-d002d002d002"), "admin.hr@neoledge.com", null, true, "Houssem", true, "Chief Talent Officer", null, "Recruiter", false, "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=", null, null, null, null, null, 1, null },
                    { new Guid("10001000-1000-1000-1000-100010001001"), null, new Guid("11111111-1111-1111-1111-111111111111"), new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), new Guid("d001d001-d001-d001-d001-d001d001d001"), "aya.t@neoledge.com", null, true, "Aya", true, "Technical Recruiter Lead", null, "Talent", false, "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=", null, null, null, null, null, 2, null },
                    { new Guid("10001000-1000-1000-1000-100010001002"), null, new Guid("11111111-1111-1111-1111-111111111111"), new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), new Guid("d001d001-d001-d001-d001-d001d001d001"), "mehdi.s@neoledge.com", null, true, "Mehdi", true, "Sourcing Consultant", null, "Sourcing", false, "6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=", null, null, null, null, null, 2, null }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("10001000-1000-1000-1000-100010001000"));

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("10001000-1000-1000-1000-100010001001"));

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("10001000-1000-1000-1000-100010001002"));

            migrationBuilder.DeleteData(
                table: "Departments",
                keyColumn: "Id",
                keyValue: new Guid("d001d001-d001-d001-d001-d001d001d001"));

            migrationBuilder.DeleteData(
                table: "Departments",
                keyColumn: "Id",
                keyValue: new Guid("d002d002-d002-d002-d002-d002d002d002"));

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AIRecommendation",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AnalyzedAt",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AutoGeneratedSummary",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_EducationScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExperienceScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Certifications",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Educations",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Languages",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Skills",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_WorkExperiences",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_IdentifiedSkills",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_OverallScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_SkillsScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_Strengths",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_TotalYearsExperience",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_Weaknesses",
                table: "JobApplications");

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis",
                table: "JobApplications",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "PlanId",
                table: "Companies",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "SubscriptionExpiresAt",
                table: "Companies",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "SubscriptionPlans",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    AnnualPrice = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    Description = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    Features = table.Column<string>(type: "text", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    MaxJobOffers = table.Column<int>(type: "integer", nullable: false),
                    MaxUsers = table.Column<int>(type: "integer", nullable: false),
                    MonthlyPrice = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    Name = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SubscriptionPlans", x => x.Id);
                });

            migrationBuilder.UpdateData(
                table: "Companies",
                keyColumn: "Id",
                keyValue: new Guid("11111111-1111-1111-1111-111111111111"),
                columns: new[] { "PlanId", "SubscriptionExpiresAt" },
                values: new object[] { new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"), null });

            migrationBuilder.InsertData(
                table: "SubscriptionPlans",
                columns: new[] { "Id", "AnnualPrice", "CreatedAt", "Description", "Features", "IsActive", "MaxJobOffers", "MaxUsers", "MonthlyPrice", "Name" },
                values: new object[,]
                {
                    { new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"), 0m, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Découverte & Essai", "[\"Offres d'emploi basiques\", \"Candidatures illimitées\", \"Support email\"]", true, 3, 5, 0m, "Free Experience" },
                    { new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"), 499m, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Pour les petites entreprises", "[\"Tout du plan Free\", \"Branding personnalisé\", \"Analyses basiques\", \"Support prioritaire\"]", true, 10, 10, 49m, "Starter" },
                    { new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"), 999m, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Pour les entreprises en croissance", "[\"Tout du plan Starter\", \"IA Scoring des candidats\", \"API Access\", \"Multi-utilisateurs avancé\", \"Support téléphonique\"]", true, 25, 25, 99m, "Professional" },
                    { new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"), 2999m, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "Solution sur-mesure MEA", "[\"Tout du plan Professional\", \"SSO\", \"Audit logs\", \"SLA garantie\", \"Compte dédié\", \"Formation\"]", true, 100, 100, 299m, "Elite Suite" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Companies_PlanId",
                table: "Companies",
                column: "PlanId");

            migrationBuilder.AddForeignKey(
                name: "FK_Companies_SubscriptionPlans_PlanId",
                table: "Companies",
                column: "PlanId",
                principalTable: "SubscriptionPlans",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
