using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class FinalizeCandidateRefactor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM \"JobApplications\";");
            migrationBuilder.DropForeignKey(
                name: "FK_JobApplications_Users_CandidateId",
                table: "JobApplications");

            migrationBuilder.DropIndex(
                name: "IX_JobApplications_Email",
                table: "JobApplications");

            migrationBuilder.DropIndex(
                name: "IX_JobApplications_SubmittedAt",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AIRecommendation",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AnalyzedAt",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_AutoGeneratedSummary",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_EducationScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExperienceScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Certifications",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Educations",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Languages",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_Skills",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_ExtractedData_WorkExperiences",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_IdentifiedSkills",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_OverallScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_SkillsScore",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_Strengths",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis_Weaknesses",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "Email",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "FirstName",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "LastName",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "LinkedInUrl",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "PhoneNumber",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "PortfolioUrl",
                table: "JobApplications");

            migrationBuilder.AlterColumn<Guid>(
                name: "CandidateId",
                table: "JobApplications",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"),
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis",
                table: "JobApplications",
                type: "jsonb",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "UserId",
                table: "JobApplications",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "Candidates",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    FirstName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    LastName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Email = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    PhoneNumber = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
                    LinkedInUrl = table.Column<string>(type: "text", nullable: true),
                    PortfolioUrl = table.Column<string>(type: "text", nullable: true),
                    MainCVUrl = table.Column<string>(type: "text", nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Candidates", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_JobApplications_AppliedAt",
                table: "JobApplications",
                column: "AppliedAt");

            migrationBuilder.CreateIndex(
                name: "IX_JobApplications_UserId",
                table: "JobApplications",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_Candidates_Email",
                table: "Candidates",
                column: "Email",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_JobApplications_Candidates_CandidateId",
                table: "JobApplications",
                column: "CandidateId",
                principalTable: "Candidates",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_JobApplications_Users_UserId",
                table: "JobApplications",
                column: "UserId",
                principalTable: "Users",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_JobApplications_Candidates_CandidateId",
                table: "JobApplications");

            migrationBuilder.DropForeignKey(
                name: "FK_JobApplications_Users_UserId",
                table: "JobApplications");

            migrationBuilder.DropTable(
                name: "Candidates");

            migrationBuilder.DropIndex(
                name: "IX_JobApplications_AppliedAt",
                table: "JobApplications");

            migrationBuilder.DropIndex(
                name: "IX_JobApplications_UserId",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "AIAnalysis",
                table: "JobApplications");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "JobApplications");

            migrationBuilder.AlterColumn<Guid>(
                name: "CandidateId",
                table: "JobApplications",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(Guid),
                oldType: "uuid");

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_AIRecommendation",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "AIAnalysis_AnalyzedAt",
                table: "JobApplications",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_AutoGeneratedSummary",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_EducationScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_ExperienceScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_ExtractedData_Certifications",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_Educations",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_ExtractedData_Languages",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_Skills",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_ExtractedData_WorkExperiences",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AIAnalysis_IdentifiedSkills",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_OverallScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AIAnalysis_SkillsScore",
                table: "JobApplications",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_Strengths",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "AIAnalysis_Weaknesses",
                table: "JobApplications",
                type: "text[]",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Email",
                table: "JobApplications",
                type: "character varying(255)",
                maxLength: 255,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "FirstName",
                table: "JobApplications",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "LastName",
                table: "JobApplications",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "LinkedInUrl",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PhoneNumber",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "PortfolioUrl",
                table: "JobApplications",
                type: "text",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_JobApplications_Email",
                table: "JobApplications",
                column: "Email");

            migrationBuilder.CreateIndex(
                name: "IX_JobApplications_SubmittedAt",
                table: "JobApplications",
                column: "SubmittedAt");

            migrationBuilder.AddForeignKey(
                name: "FK_JobApplications_Users_CandidateId",
                table: "JobApplications",
                column: "CandidateId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
