CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Companies" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Description" character varying(500),
    "ContactEmail" character varying(255),
    "ContactPhone" text,
    "Address" character varying(500),
    "City" character varying(100),
    "PostalCode" character varying(20),
    "Country" character varying(100),
    "LogoUrl" text,
    "PrimaryColor" character varying(7) NOT NULL DEFAULT '#FFD700',
    "SecondaryColor" character varying(7) NOT NULL DEFAULT '#000000',
    "IsActive" boolean NOT NULL,
    "PlanId" uuid NOT NULL,
    "PlanName" character varying(50) NOT NULL,
    "PlanDescription" character varying(200),
    "PlanMonthlyPrice" numeric(18,2) NOT NULL,
    "PlanAnnualPrice" numeric(18,2) NOT NULL,
    "PlanMaxUsers" integer NOT NULL,
    "PlanMaxJobOffers" integer NOT NULL,
    "PlanFeatures" text NOT NULL,
    "PlanIsActive" boolean NOT NULL,
    "PlanCreatedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "SubscriptionExpiresAt" timestamp with time zone,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "PhoneNumber" text,
    "CompanyId" uuid,
    "Role" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "EmailConfirmed" boolean NOT NULL,
    "EmailConfirmationToken" text,
    "PasswordResetToken" text,
    "PasswordResetTokenExpiry" timestamp with time zone,
    "RefreshToken" text,
    "RefreshTokenExpiry" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL
);

CREATE TABLE "JobOffers" (
    "Id" uuid NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text NOT NULL,
    "Type" integer NOT NULL,
    "Location" character varying(100),
    "SalaryRange" text,
    "CompanyId" uuid NOT NULL,
    "CreatedById" uuid NOT NULL,
    "FormConfig_RequireCV" boolean NOT NULL,
    "FormConfig_RequireCoverLetter" boolean NOT NULL,
    "FormConfig_RequirePortfolio" boolean NOT NULL,
    "FormConfig_RequireLinkedIn" boolean NOT NULL,
    "FormConfig_CustomFields" text NOT NULL,
    "FormConfig_RequiredDocuments" text NOT NULL,
    "DisplayConfig_ShowCompanyName" boolean NOT NULL,
    "DisplayConfig_ShowCompanyLogo" boolean NOT NULL,
    "DisplayConfig_ShowSalary" boolean NOT NULL,
    "DisplayConfig_ShowLocation" boolean NOT NULL,
    "DisplayConfig_CustomCSS" text,
    "DisplayConfig_HeaderImageUrl" text,
    "PublicUrl" character varying(500),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "PublishedAt" timestamp with time zone,
    "ExpiresAt" timestamp with time zone,
    CONSTRAINT "PK_JobOffers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobOffers_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobOffers_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "JobApplications" (
    "Id" uuid NOT NULL,
    "JobOfferId" uuid NOT NULL,
    "CandidateId" uuid,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PhoneNumber" text,
    "CVUrl" text NOT NULL,
    "CoverLetterUrl" text,
    "PortfolioUrl" text,
    "LinkedInUrl" text,
    "CustomFieldsData" text NOT NULL,
    "Status" integer NOT NULL,
    "AIAnalysis_OverallScore" integer,
    "AIAnalysis_ExperienceScore" integer,
    "AIAnalysis_EducationScore" integer,
    "AIAnalysis_SkillsScore" integer,
    "AIAnalysis_ExtractedData_WorkExperiences" text,
    "AIAnalysis_ExtractedData_Educations" text,
    "AIAnalysis_ExtractedData_Skills" text,
    "AIAnalysis_ExtractedData_Languages" text[],
    "AIAnalysis_ExtractedData_Certifications" text[],
    "AIAnalysis_AutoGeneratedSummary" text,
    "AIAnalysis_IdentifiedSkills" text,
    "AIAnalysis_Strengths" text[],
    "AIAnalysis_Weaknesses" text[],
    "AIAnalysis_AIRecommendation" text,
    "AIAnalysis_AnalyzedAt" timestamp with time zone,
    "RecruiterNotes" text,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ReviewedAt" timestamp with time zone,
    "ReviewedById" uuid,
    CONSTRAINT "PK_JobApplications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobApplications_JobOffers_JobOfferId" FOREIGN KEY ("JobOfferId") REFERENCES "JobOffers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobApplications_Users_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_JobApplications_Users_ReviewedById" FOREIGN KEY ("ReviewedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Companies" ("Id", "Address", "City", "ContactEmail", "ContactPhone", "Country", "CreatedAt", "Description", "IsActive", "LogoUrl", "Name", "PostalCode", "PrimaryColor", "SecondaryColor", "SubscriptionExpiresAt", "UpdatedAt", "PlanAnnualPrice", "PlanCreatedAt", "PlanDescription", "PlanFeatures", "PlanId", "PlanIsActive", "PlanMaxJobOffers", "PlanMaxUsers", "PlanMonthlyPrice", "PlanName")
VALUES ('11111111-1111-1111-1111-111111111111', NULL, NULL, 'contact@neoledge.com', NULL, NULL, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Société de démonstration pour la plateforme', TRUE, NULL, 'NeoLedge Demo Company', NULL, '#FFD700', '#000000', NULL, NULL, 2999.0, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Solution sur mesure pour grandes entreprises', '["Tout du plan Professional", "SSO", "Audit logs", "SLA garantie", "Compte dédié", "Formation"]', 'dddddddd-dddd-dddd-dddd-dddddddddddd', TRUE, 100, 100, 299.0, 'Enterprise');

INSERT INTO "Users" ("Id", "CompanyId", "CreatedAt", "Email", "EmailConfirmationToken", "EmailConfirmed", "FirstName", "IsActive", "LastLoginAt", "LastName", "PasswordHash", "PasswordResetToken", "PasswordResetTokenExpiry", "PhoneNumber", "RefreshToken", "RefreshTokenExpiry", "Role", "UpdatedAt")
VALUES ('22222222-2222-2222-2222-222222222222', NULL, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'admin@neoledge.com', NULL, TRUE, 'Admin', TRUE, NULL, 'NeoLedge', '6G94qKPK8LYNjnTllCqm2G3BUM08AzOK7yW30tfjrMc=', NULL, NULL, NULL, NULL, NULL, 0, NULL);

CREATE INDEX "IX_Companies_Name" ON "Companies" ("Name");

CREATE INDEX "IX_JobApplications_CandidateId" ON "JobApplications" ("CandidateId");

CREATE INDEX "IX_JobApplications_Email" ON "JobApplications" ("Email");

CREATE INDEX "IX_JobApplications_JobOfferId" ON "JobApplications" ("JobOfferId");

CREATE INDEX "IX_JobApplications_ReviewedById" ON "JobApplications" ("ReviewedById");

CREATE INDEX "IX_JobApplications_Status" ON "JobApplications" ("Status");

CREATE INDEX "IX_JobApplications_SubmittedAt" ON "JobApplications" ("SubmittedAt");

CREATE INDEX "IX_JobOffers_CompanyId" ON "JobOffers" ("CompanyId");

CREATE INDEX "IX_JobOffers_CreatedById" ON "JobOffers" ("CreatedById");

CREATE INDEX "IX_JobOffers_PublishedAt" ON "JobOffers" ("PublishedAt");

CREATE INDEX "IX_JobOffers_Status" ON "JobOffers" ("Status");

CREATE INDEX "IX_Users_CompanyId" ON "Users" ("CompanyId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260303013308_InitialCreate', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "Industry" character varying(100);

ALTER TABLE "Companies" ADD "Size" character varying(50);

UPDATE "Companies" SET "Industry" = NULL, "Size" = NULL
WHERE "Id" = '11111111-1111-1111-1111-111111111111';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304003742_AddCompanyIndustryAndSize', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "AvatarUrl" text;

UPDATE "Users" SET "AvatarUrl" = NULL
WHERE "Id" = '22222222-2222-2222-2222-222222222222';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305175104_AddUserAvatarUrl', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "Department" character varying(100);

ALTER TABLE "JobApplications" ADD "AiScore" integer;

ALTER TABLE "JobApplications" ADD "AppliedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

UPDATE "Users" SET "Department" = NULL
WHERE "Id" = '22222222-2222-2222-2222-222222222222';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305185509_AddMissingFieldsForDemocking', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ADD "ShareToken" character varying(100);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305214524_AddShareTokenToJobOffers', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ADD "Deadline" timestamp with time zone;

ALTER TABLE "JobOffers" ADD "Department" text;

ALTER TABLE "JobOffers" ADD "ExperienceLevel" integer;

ALTER TABLE "JobOffers" ADD "RemotePolicy" integer;

ALTER TABLE "JobOffers" ADD "Skills" text[];

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310121637_ExpandJobOfferSchema', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ALTER COLUMN "Skills" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310122929_FixJobOfferSkillsMapping', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ALTER COLUMN "Skills" DROP NOT NULL;

ALTER TABLE "JobOffers" ALTER COLUMN "RemotePolicy" DROP NOT NULL;

ALTER TABLE "JobOffers" ALTER COLUMN "ExperienceLevel" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310123622_MakeJobOfferFieldsNullable', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ADD "FormConfig_RequireEmail" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "JobOffers" ADD "FormConfig_RequireFullName" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "JobOffers" ADD "FormConfig_RequirePhone" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260311195748_AddFormConfigFields', '10.0.3');

COMMIT;

START TRANSACTION;
CREATE TABLE "Interviews" (
    "Id" uuid NOT NULL,
    "JobApplicationId" uuid NOT NULL,
    "RecruiterId" uuid NOT NULL,
    "ScheduledAt" timestamp with time zone NOT NULL,
    "Type" character varying(20) NOT NULL,
    "LocationOrLink" character varying(500),
    "Message" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Interviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Interviews_JobApplications_JobApplicationId" FOREIGN KEY ("JobApplicationId") REFERENCES "JobApplications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Interviews_Users_RecruiterId" FOREIGN KEY ("RecruiterId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Interviews_JobApplicationId" ON "Interviews" ("JobApplicationId");

CREATE INDEX "IX_Interviews_RecruiterId" ON "Interviews" ("RecruiterId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312155739_AddInterviewsTable', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobOffers" ADD "WeightEducation" integer NOT NULL DEFAULT 0;

ALTER TABLE "JobOffers" ADD "WeightExperience" integer NOT NULL DEFAULT 0;

ALTER TABLE "JobOffers" ADD "WeightSkills" integer NOT NULL DEFAULT 0;

CREATE TABLE "JobApplicationComments" (
    "Id" uuid NOT NULL,
    "JobApplicationId" uuid NOT NULL,
    "AuthorId" uuid NOT NULL,
    "Content" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ParentCommentId" uuid,
    CONSTRAINT "PK_JobApplicationComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_JobApplicationComments_JobApplications_JobApplicationId" FOREIGN KEY ("JobApplicationId") REFERENCES "JobApplications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobApplicationComments_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_JobApplicationComments_AuthorId" ON "JobApplicationComments" ("AuthorId");

CREATE INDEX "IX_JobApplicationComments_JobApplicationId" ON "JobApplicationComments" ("JobApplicationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312214103_AddCollaborativeCommentsAndJobWeights', '10.0.3');

COMMIT;

START TRANSACTION;
DELETE FROM "JobApplications";

ALTER TABLE "JobApplications" DROP CONSTRAINT "FK_JobApplications_Users_CandidateId";

DROP INDEX "IX_JobApplications_Email";

DROP INDEX "IX_JobApplications_SubmittedAt";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_AIRecommendation";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_AnalyzedAt";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_AutoGeneratedSummary";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_EducationScore";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExperienceScore";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExtractedData_Certifications";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExtractedData_Educations";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExtractedData_Languages";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExtractedData_Skills";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_ExtractedData_WorkExperiences";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_IdentifiedSkills";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_OverallScore";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_SkillsScore";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_Strengths";

ALTER TABLE "JobApplications" DROP COLUMN "AIAnalysis_Weaknesses";

ALTER TABLE "JobApplications" DROP COLUMN "Email";

ALTER TABLE "JobApplications" DROP COLUMN "FirstName";

ALTER TABLE "JobApplications" DROP COLUMN "LastName";

ALTER TABLE "JobApplications" DROP COLUMN "LinkedInUrl";

ALTER TABLE "JobApplications" DROP COLUMN "PhoneNumber";

ALTER TABLE "JobApplications" DROP COLUMN "PortfolioUrl";

UPDATE "JobApplications" SET "CandidateId" = '00000000-0000-0000-0000-000000000000' WHERE "CandidateId" IS NULL;
ALTER TABLE "JobApplications" ALTER COLUMN "CandidateId" SET NOT NULL;
ALTER TABLE "JobApplications" ALTER COLUMN "CandidateId" SET DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "JobApplications" ADD "AIAnalysis" jsonb;

ALTER TABLE "JobApplications" ADD "UserId" uuid;

CREATE TABLE "Candidates" (
    "Id" uuid NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PhoneNumber" character varying(20),
    "LinkedInUrl" text,
    "PortfolioUrl" text,
    "MainCVUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Candidates" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_JobApplications_AppliedAt" ON "JobApplications" ("AppliedAt");

CREATE INDEX "IX_JobApplications_UserId" ON "JobApplications" ("UserId");

CREATE UNIQUE INDEX "IX_Candidates_Email" ON "Candidates" ("Email");

ALTER TABLE "JobApplications" ADD CONSTRAINT "FK_JobApplications_Candidates_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Candidates" ("Id") ON DELETE CASCADE;

ALTER TABLE "JobApplications" ADD CONSTRAINT "FK_JobApplications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314164820_FinalizeCandidateRefactor', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobApplications" DROP COLUMN "SubmittedAt";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314195746_FixEmailVerification', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "MustChangePassword" boolean NOT NULL DEFAULT FALSE;

UPDATE "Users" SET "MustChangePassword" = FALSE
WHERE "Id" = '22222222-2222-2222-2222-222222222222';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314210721_AddMustChangePassword', '10.0.3');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318125149_NovahireDB', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "Website" character varying(255);

UPDATE "Companies" SET "Website" = NULL
WHERE "Id" = '11111111-1111-1111-1111-111111111111';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260319134346_AddCompanyWebsite', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" DROP COLUMN "Department";

ALTER TABLE "Users" ADD "DepartmentId" uuid;

CREATE TABLE "Departments" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "CompanyId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Departments_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

UPDATE "Users" SET "DepartmentId" = NULL
WHERE "Id" = '22222222-2222-2222-2222-222222222222';

CREATE INDEX "IX_Users_DepartmentId" ON "Users" ("DepartmentId");

CREATE INDEX "IX_Departments_CompanyId" ON "Departments" ("CompanyId");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260319221339_AddDepartmentEntity', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" DROP COLUMN "PlanAnnualPrice";

ALTER TABLE "Companies" DROP COLUMN "PlanCreatedAt";

ALTER TABLE "Companies" DROP COLUMN "PlanDescription";

ALTER TABLE "Companies" DROP COLUMN "PlanFeatures";

ALTER TABLE "Companies" DROP COLUMN "PlanIsActive";

ALTER TABLE "Companies" DROP COLUMN "PlanMaxJobOffers";

ALTER TABLE "Companies" DROP COLUMN "PlanMaxUsers";

ALTER TABLE "Companies" DROP COLUMN "PlanMonthlyPrice";

ALTER TABLE "Companies" DROP COLUMN "PlanName";

ALTER TABLE "Companies" ALTER COLUMN "PlanId" DROP NOT NULL;

CREATE TABLE "ActivityLogs" (
    "Id" uuid NOT NULL,
    "Action" text NOT NULL,
    "Details" text,
    "UserId" uuid,
    "UserEmail" text,
    "CompanyId" uuid,
    "EntityType" text,
    "EntityId" text,
    "Timestamp" timestamp with time zone NOT NULL,
    "IPAddress" text,
    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id")
);

CREATE TABLE "SubscriptionPlans" (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200),
    "MonthlyPrice" numeric(18,2) NOT NULL,
    "AnnualPrice" numeric(18,2) NOT NULL,
    "MaxUsers" integer NOT NULL,
    "MaxJobOffers" integer NOT NULL,
    "Features" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

INSERT INTO "SubscriptionPlans" ("Id", "AnnualPrice", "CreatedAt", "Description", "Features", "IsActive", "MaxJobOffers", "MaxUsers", "MonthlyPrice", "Name")
VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 0.0, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Plan gratuit pour découvrir la plateforme', '["Offres d''emploi basiques", "Candidatures illimitées", "Support email"]', TRUE, 3, 5, 0.0, 'Free');
INSERT INTO "SubscriptionPlans" ("Id", "AnnualPrice", "CreatedAt", "Description", "Features", "IsActive", "MaxJobOffers", "MaxUsers", "MonthlyPrice", "Name")
VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 499.0, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Pour les petites entreprises', '["Tout du plan Free", "Branding personnalisé", "Analyses basiques", "Support prioritaire"]', TRUE, 10, 10, 49.0, 'Starter');
INSERT INTO "SubscriptionPlans" ("Id", "AnnualPrice", "CreatedAt", "Description", "Features", "IsActive", "MaxJobOffers", "MaxUsers", "MonthlyPrice", "Name")
VALUES ('cccccccc-cccc-cccc-cccc-cccccccccccc', 999.0, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Pour les entreprises en croissance', '["Tout du plan Starter", "IA Scoring des candidats", "API Access", "Multi-utilisateurs avancé", "Support téléphonique"]', TRUE, 25, 25, 99.0, 'Professional');
INSERT INTO "SubscriptionPlans" ("Id", "AnnualPrice", "CreatedAt", "Description", "Features", "IsActive", "MaxJobOffers", "MaxUsers", "MonthlyPrice", "Name")
VALUES ('dddddddd-dddd-dddd-dddd-dddddddddddd', 2999.0, TIMESTAMPTZ '2024-01-01T00:00:00Z', 'Solution sur mesure pour grandes entreprises', '["Tout du plan Professional", "SSO", "Audit logs", "SLA garantie", "Compte dédié", "Formation"]', TRUE, 100, 100, 299.0, 'Enterprise');

CREATE INDEX "IX_Companies_PlanId" ON "Companies" ("PlanId");

ALTER TABLE "Companies" ADD CONSTRAINT "FK_Companies_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260320022207_SuperAdminOverhaul', '10.0.3');

COMMIT;

START TRANSACTION;
UPDATE "SubscriptionPlans" SET "Description" = 'Découverte & Essai', "Name" = 'Free Experience'
WHERE "Id" = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';

UPDATE "SubscriptionPlans" SET "Description" = 'Solution sur-mesure MEA', "Name" = 'Elite Suite'
WHERE "Id" = 'dddddddd-dddd-dddd-dddd-dddddddddddd';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260320031748_RenameSubscriptionPlans', '10.0.3');

COMMIT;

START TRANSACTION;
ALTER TABLE "JobApplicationComments" ADD "UpdatedAt" timestamp with time zone;

ALTER TABLE "Interviews" ADD "Status" integer NOT NULL DEFAULT 0;

ALTER TABLE "Interviews" ADD "UpdatedAt" timestamp with time zone;

CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "JobApplicationId" uuid NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "Type" text,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_JobApplications_JobApplicationId" FOREIGN KEY ("JobApplicationId") REFERENCES "JobApplications" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Notifications_JobApplicationId" ON "Notifications" ("JobApplicationId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260402224056_InterviewAndCleanup', '10.0.3');

COMMIT;

