"""
NovaHire AI Service - Data Models
All Pydantic models for requests, responses, jobs, and internal pipeline data.
"""

from __future__ import annotations
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from enum import Enum
from datetime import datetime


# ──────────────────────────────────────────────
# Enums
# ──────────────────────────────────────────────

class AnalysisMode(str, Enum):
    FULL = "full_analysis"
    EXTRACT_ONLY = "extract_only"
    SCORE_ONLY = "score_only"


class JobStatus(str, Enum):
    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    RETRYING = "retrying"


# ──────────────────────────────────────────────
# Pipeline Stage Data
# ──────────────────────────────────────────────

class ExtractionResult(BaseModel):
    raw_text: str = ""
    method: str = "pdfplumber"  # pdfplumber | pymupdf | docx2txt | python-docx | tesseract | easyocr
    file_format: str = "pdf"    # pdf | docx | image
    page_count: int = 0
    char_count: int = 0


class ParsedEntities(BaseModel):
    email: Optional[str] = None
    phone: Optional[str] = None
    skills: List[str] = Field(default_factory=list)
    total_experience_years: float = 0.0
    education_score: float = 50.0
    languages: List[str] = Field(default_factory=list)
    summary: str = ""
    work_experiences: List[dict] = Field(default_factory=list)
    educations: List[dict] = Field(default_factory=list)


class TextSections(BaseModel):
    experience: str = ""
    education: str = ""
    skills: str = ""
    other: str = ""


class ScoringResult(BaseModel):
    experience_score: float = 0.0
    education_score: float = 0.0
    skills_score: float = 0.0
    language_score: float = 0.0
    overall_score: float = 0.0
    seniority_level: str = "MID"
    total_years: float = 0.0
    weights_used: Dict[str, float] = Field(default_factory=dict)


class LanguageResult(BaseModel):
    detected: List[str] = Field(default_factory=list)
    requirements: List[Dict[str, str]] = Field(default_factory=list)
    match_score: float = 100.0
    gaps: List[str] = Field(default_factory=list)


# ──────────────────────────────────────────────
# Work Experience / Education (extracted)
# ──────────────────────────────────────────────

class WorkExperience(BaseModel):
    job_title: str = ""
    company: str = ""
    location: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    is_current: bool = False
    description: Optional[str] = None


class Education(BaseModel):
    degree: str = ""
    institution: str = ""
    field_of_study: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    gpa: Optional[str] = None


# ──────────────────────────────────────────────
# API Response (backward compatible with old format)
# ──────────────────────────────────────────────

class AnalysisResponse(BaseModel):
    overallScore: int = 0
    experienceScore: int = 0
    educationScore: int = 0
    skillsScore: int = 0
    totalYearsExperience: float = 0.0
    autoGeneratedSummary: str = ""
    identifiedSkills: List[str] = Field(default_factory=list)
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    aiRecommendation: str = ""
    confidenceScore: float = 0.0
    extractedData: dict = Field(default_factory=dict)
    rawCvText: str = ""
    interviewQuestions: List[Dict[str, str]] = Field(default_factory=list)


# ──────────────────────────────────────────────
# Job Queue Models
# ──────────────────────────────────────────────

class JobSubmission(BaseModel):
    job_title: str
    job_description: str
    weight_experience: int = 33
    weight_education: int = 33
    weight_skills: int = 34
    mode: AnalysisMode = AnalysisMode.FULL
    language: str = "fr"  # fr | en | ar


class JobRecord(BaseModel):
    job_id: str
    status: JobStatus = JobStatus.QUEUED
    mode: AnalysisMode = AnalysisMode.FULL
    created_at: datetime = Field(default_factory=datetime.utcnow)
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retries: int = 0
    max_retries: int = 3
    error: Optional[str] = None
    result: Optional[AnalysisResponse] = None
    stage_timings: Dict[str, float] = Field(default_factory=dict)


class JobStatusResponse(BaseModel):
    job_id: str
    status: JobStatus
    created_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    retries: int = 0
    error: Optional[str] = None
    result: Optional[AnalysisResponse] = None
    stage_timings: Dict[str, float] = Field(default_factory=dict)


# ──────────────────────────────────────────────
# Metrics
# ──────────────────────────────────────────────

class StageMetric(BaseModel):
    name: str
    count: int = 0
    total_ms: float = 0.0
    p50_ms: float = 0.0
    p95_ms: float = 0.0
    p99_ms: float = 0.0
    error_count: int = 0


# ──────────────────────────────────────────────
# Quiz Generation Models
# ──────────────────────────────────────────────

class QuizQuestionModel(BaseModel):
    text: str
    options: List[str]
    correctAnswerIndex: int
    explanation: str
    type: str  # "Technical" | "SoftSkill"

class QuizRequest(BaseModel):
    jobTitle: str
    jobDescription: str
    numQuestions: int = 10
    language: str = "fr"
    difficulty: str = "Mid"
    topics: List[str] = Field(default_factory=list)

class QuizResponse(BaseModel):
    title: str
    description: str
    questions: List[QuizQuestionModel]

# ──────────────────────────────────────────────
# Job Description Generation Models
# ──────────────────────────────────────────────

class JDGenerationRequest(BaseModel):
    jobTitle: str
    keywords: Optional[str] = None
    language: str = "fr"

class JDGenerationResponse(BaseModel):
    description: str

# ──────────────────────────────────────────────
# Feedback Generation Models
# ──────────────────────────────────────────────

class FeedbackRequest(BaseModel):
    candidateName: str
    jobTitle: str
    recruiterNotes: str
    language: str = "fr"

class FeedbackResponse(BaseModel):
    feedback: str

class OfferLetterRequest(BaseModel):
    candidateName: str
    jobTitle: str
    salary: float
    currency: str = "DT"
    startDate: str
    benefits: str
    recruiterName: str
    companyName: str
    language: str = "fr"

class OfferLetterResponse(BaseModel):
    offerLetter: str
