using System;
using System.Collections.Generic;

namespace Application.DTOs.AI
{
    public class AIAnalysisResponseDto
    {
        public int OverallScore { get; set; }
        public int ExperienceScore { get; set; }
        public int EducationScore { get; set; }
        public int SkillsScore { get; set; }
        public double TotalYearsExperience { get; set; }
        public string AutoGeneratedSummary { get; set; } = string.Empty;
        public List<string> IdentifiedSkills { get; set; } = new List<string>();
        public List<string> Strengths { get; set; } = new List<string>();
        public List<string> Weaknesses { get; set; } = new List<string>();
        public string AIRecommendation { get; set; } = string.Empty;
        public ExtractedDataDto ExtractedData { get; set; } = new ExtractedDataDto();
        public string RawCvText { get; set; } = string.Empty;
        public List<InterviewQuestionDto> InterviewQuestions { get; set; } = new List<InterviewQuestionDto>();
    }

    public class InterviewQuestionDto
    {
        public string Category { get; set; } = string.Empty;
        public string Question { get; set; } = string.Empty;
        public string Purpose { get; set; } = string.Empty;
        public int? Score { get; set; }
        public string? Notes { get; set; }
    }

    public class ExtractedDataDto
    {
        public List<WorkExperienceDto> WorkExperiences { get; set; } = new List<WorkExperienceDto>();
        public List<EducationDto> Educations { get; set; } = new List<EducationDto>();
        public List<string> Skills { get; set; } = new List<string>();
        public List<string> Languages { get; set; } = new List<string>();
        public List<string> Certifications { get; set; } = new List<string>();
    }

    public class WorkExperienceDto
    {
        public string JobTitle { get; set; } = string.Empty;
        public string Company { get; set; } = string.Empty;
        public string? Location { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public bool IsCurrent { get; set; }
        public string? Description { get; set; }
    }

    public class EducationDto
    {
        public string Degree { get; set; } = string.Empty;
        public string Institution { get; set; } = string.Empty;
        public string? FieldOfStudy { get; set; }
        public string? StartDate { get; set; }
        public string? EndDate { get; set; }
        public string? GPA { get; set; }
    }
}
