using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entities
{
    /// <summary>
    /// Entité JobApplication - Représente une candidature à une offre
    /// </summary>
    public class JobApplication
    {
        [Key]
        public Guid Id { get; set; }

        // Lien avec l'offre
        [Required]
        public Guid JobOfferId { get; set; }
        public virtual JobOffer? JobOffer { get; set; } // Made nullable

        // Lien avec le candidat (Identité et Profil)
        [Required]
        public Guid CandidateId { get; set; }
        public virtual Candidate? Candidate { get; set; }

        // Documents de candidature (Spécifiques à ce poste)
        [Required]
        public required string CVUrl { get; set; } // URL du CV pour cette candidature spécifique

        public string? CoverLetterUrl { get; set; } // Made nullable

        // Champs personnalisés configurés pour l'offre
        public Dictionary<string, string> CustomFieldsData { get; set; } = new Dictionary<string, string>();

        // Statut de la candidature
        public ApplicationStatus Status { get; set; } = ApplicationStatus.Submitted;

        // Origine de la candidature (ex: LinkedIn, Indeed, Direct)
        public string? Source { get; set; }

        // Résultats de l'analyse IA
        public AIAnalysisResult? AIAnalysis { get; set; } // Made nullable

        // Score IA (Cache for performance)
        public int? AiScore { get; set; }

        // Notes du recruteur
        public string? RecruiterNotes { get; set; } // Made nullable

        // Quiz Tracking
        public bool QuizSent { get; set; } = false;
        public int? QuizScore { get; set; }
        public DateTime? QuizExpiresAt { get; set; }

        // Offer Management
        public string? OfferLetterContent { get; set; }

        public virtual ICollection<JobApplicationComment> Comments { get; set; } = new List<JobApplicationComment>();
        public virtual ICollection<ApplicationRating> Ratings { get; set; } = new List<ApplicationRating>();
        public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

        // Timestamps
        public DateTime AppliedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }
        public DateTime? ReviewedAt { get; set; }

        // Qui a examiné la candidature
        public Guid? ReviewedById { get; set; }
        public virtual User? ReviewedBy { get; set; } // Made nullable

        // Méthodes utilitaires

        public void UpdateStatus(ApplicationStatus newStatus, Guid reviewerId)
        {
            Status = newStatus;
            ReviewedById = reviewerId;
            ReviewedAt = DateTime.UtcNow;
            UpdatedAt = DateTime.UtcNow;
        }
    }

    /// <summary>
    /// Statuts d'une candidature
    /// </summary>
    public enum ApplicationStatus
    {
        Submitted = 0,      // Soumise
        UnderReview = 1,    // En cours d'examen
        Shortlisted = 2,    // Présélectionné
        Interview = 3,      // Entretien prévu
        Interviewed = 6,    // Entretien réalisé
        Rejected = 4,       // Rejeté
        Accepted = 5,       // Accepté
        OfferSent = 7       // Offre Envoyée
    }

    /// <summary>
    /// Résultats de l'analyse IA
    /// </summary>
    public class AIAnalysisResult
    {
        // Score global (0-100)
        public int OverallScore { get; set; }

        // Scores détaillés
        public int ExperienceScore { get; set; }
        public int EducationScore { get; set; }
        public int SkillsScore { get; set; }

        // Séniorité totale calculée en années
        public double TotalYearsExperience { get; set; }

        // Extraction de données du CV
        public ExtractedCVData? ExtractedData { get; set; } // Made nullable

        // Résumé automatique généré par LLM
        public string? AutoGeneratedSummary { get; set; } // Made nullable

        // Compétences identifiées
        public List<string> IdentifiedSkills { get; set; } = new List<string>();

        // Points forts / Points faibles
        public List<string> Strengths { get; set; } = new List<string>();
        public List<string> Weaknesses { get; set; } = new List<string>();
        public List<InterviewQuestionRecord> InterviewQuestions { get; set; } = new List<InterviewQuestionRecord>();

        // Recommandation IA
        public string? AIRecommendation { get; set; } // Made nullable

        // Timestamp de l'analyse
        public DateTime AnalyzedAt { get; set; } = DateTime.UtcNow;
    }

    /// <summary>
    /// Données extraites du CV par OCR/NLP
    /// </summary>
    public class ExtractedCVData
    {
        public List<WorkExperience> WorkExperiences { get; set; } = new List<WorkExperience>();
        public List<Education> Educations { get; set; } = new List<Education>();
        public List<string> Skills { get; set; } = new List<string>();
        public List<string> Languages { get; set; } = new List<string>();
        public List<string> Certifications { get; set; } = new List<string>();
    }

    public class WorkExperience
    {
        public required string JobTitle { get; set; } // Use required
        public required string Company { get; set; } // Use required
        public string? Location { get; set; } // Made nullable
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool IsCurrent { get; set; }
        public string? Description { get; set; } // Made nullable
    }

    public class Education
    {
        public required string Degree { get; set; } // Use required
        public required string Institution { get; set; } // Use required
        public string? FieldOfStudy { get; set; } // Made nullable
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string? GPA { get; set; } // Made nullable
    }

    public class InterviewQuestionRecord
    {
        public string Category { get; set; } = string.Empty;
        public string Question { get; set; } = string.Empty;
        public string Purpose { get; set; } = string.Empty;
        public int? Score { get; set; } // Added for Live Mode (1-5)
        public string? Notes { get; set; } // Added for Live Mode
    }
}